function [func] = shapeFunction(type)
% Returns shape function for triangular elements



switch type
    case 'T3'
        func = @shapeFunctionT3;
    case 'T6'
        func = @shapeFunctionT6;
end


function [shape,naturalDerivatives] = shapeFunctionT3(xi2,xi3)

shape = [1-xi2-xi3, ...
    xi2, ...
    xi3];
     
naturalDerivatives = [-1, 1, 0;
    -1, 0, 1];
end


function [shape,naturalDerivatives] = shapeFunctionT6(xi2,xi3)

shape = [ (1-xi2-xi3)*(2*(1-xi2-xi3)-1), ...
    xi2*(2*xi2-1), ...
    xi3*(2*xi3-1), ...
    4*(1-xi2-xi3)*xi2, ...
    4*xi2*xi3, ...
    4*xi3*(1-xi2-xi3)];
     
naturalDerivatives = [4*xi2 + 4*xi3 - 3, ...
    4*xi2 - 1, ...
    0, ...
    4 - 4*xi3 - 8*xi2, ...
    4*xi3, ...
    -4*xi3; ...
    4*xi2 + 4*xi3 - 3, ...
    0, ...
    4*xi3 - 1, ...
    -4*xi2, ...
    4*xi2, ...
    4 - 8*xi3 - 4*xi2];
end

end % end function

